name: Your Workflow Name
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hello_world/requirements.txt  

      - name: Coverage report
        run: |
          pip install coverage
          coverage run hello_world/manage.py test
          coverage report

      - name: Django Testing
        run: python hello_world/manage.py test
